INSERT [dbo].[role] ([role_name]) VALUES (N'CANDIDATE')
INSERT [dbo].[role] ([role_name]) VALUES (N'HREMPLOYEE')
INSERT [dbo].[role] ([role_name]) VALUES (N'HRMANAGER')
INSERT [dbo].[role] ([role_name]) VALUES (N'INTERVIEWER')
INSERT [dbo].[role] ([role_name]) VALUES (N'ADMIN')